### ISSUE TITLE
mmp.areatabler not defined

### ISSUE THREAD

**Issue by csmall** [IRE-Mudlet-Mapping/ire-mapping-script#17] opened 2016-09-24 22:03 UTC
I have had a lot of the mapping functions fail on me. Debugging the problem they all complain that mmp.areatabler is not defined. Indeed if I run 

> lua display(mmp.areatabler)

it displays nil.

The work-around is to type

> lua mmp_regenerate_areas()

when I first log in.

Looking at the code, I can see no place where mmp.areatabler is defined except in that function. I would have thought it may have been loaded from a file once generated.

To me the fix is either:
- save/load mmp.areatabler when you logout/login
- Add mmp_regenerate_areas() when you login, perhaps even conditional if mmp.areatabler is nil

I cannot see how, but I assume it has something to do with me upgrading from 3.0.0-delta to the latest in the release_30 git repository. That's where the problem happened OR because release_30 enabled me to download a new map, the problem is with the download and process map code.

**Comment by csmall** [comment] 2016-09-25 06:18
So, this is how it seems to happen:
* a bunch of mapper functions fail because mmp.areatabler is nil
* this array is created in the function mmp_regenerate_areas()
* that function is called if either event of "mmp areas changed" or "mmapper map reloaded" fires
* mmapper map reloaded is raised by mmp.map_data_changed
* mmp.map_data_changed has 4 event handlers

So!
I know that mmp.map_data_changed is not being called (I put a cecho in it) so I think something happened to the events being fired in release_30.

**Comment by jgh713** [comment] 2016-09-25 21:23
I'm having a similar issue having upgraded to a dev compile of a newer 3.0. It seems to be caused by the fact that the map isn't loaded before the scripts anymore. In the mudlet I've got, the map isn't loaded at all until you open a map window. I have to open my map before I run mmp.init() (which runs the mmp_regenerate_areas() function and fixes a few other quirks caused by the function failing). I'm not sure what would need to be changed for that to work properly, honestly. I'll fiddle with 3.0, but it's really a pain.

**Comment by vadi2** [comment] 2016-09-26 01:30
That's always been the case, the map is loaded only when the mapper is
open. Do you have a script to create the mapper widget?

**Comment by jgh713** [comment] 2016-09-26 19:17
@vadi2 I'd always been able to use goto and related mapper functions without opening the map window. No script to open the mapper. At least, not that I knew of.

**Comment by SlySven** [comment] 2016-10-09 06:10
Curious - Is your "map window" inside a Geyser (or possible Vyzor) window or is it in a separate dockable widget?

If it is the latter then yes, I can confirm that the map is not loaded until the map widget is created - whereas if it is part of a scripted system then it is loaded during start-up for the former....

**Comment by jgh713** [comment] 2016-10-09 07:11
Mudlet 2.1 - Fresh profile: https://ada-young.appspot.com/pastebin/PEztZ-1T

Map data is all available. Works the same using 3.0.0-delta fresh from the site.

Mudlet 3.0 dev (308 i think?) - Fresh profile: https://ada-young.appspot.com/pastebin/4qhASVcX

Map has to be opened for any map data to be available, due to map audit.

Map data is available from the moment the mapper is loaded, unless there's something I seem to be missing.

**Comment by SlySven** [comment] 2016-10-09 18:14
The issue for Mudlet is that it only allows one mapper per profile and if there is a map fitted into a scripted system that takes "ownership" of the mapper and you cannot then have a dockable widget one.

This is why the latter is not created until it is requested and one has not already been made by a script.

Incidentally, if you comment out code in a script that uses geyser/vyzor to make a map and click to created a dock-widget one and edited the script to remove the comment and rerun the script in the same session it will create a mapper as per the script - _but it leaves an orphaned dockable widget one_ which appears to operate but will IIRC then crash when you try to change area with the selector in it's controls!

The same sort of thing about NOT clearing up the dockable mapper is an issue when running Mudlet and _multi-playing_ {see Mudlet bug [1229493](https://bugs.launchpad.net/mudlet/+bug/1229493)}: closing one profile that has such a mapper does not remove the dockwidget from the application and restarting another instance of the same profile in the same session will produce a fresh, new dockable mapper - and doing things with the orphaned one is likely to produce a crash in the same way... :unamused: 

> Map data is available from the moment the mapper is loaded, unless there's something I seem to be missing.

It is more the case that the mapper is available from the point the map data is loaded (or for a _virgin_ profile from the point the user decides to download an IRE Map if that is an option or create their own) - if I recall correctly.

**Comment by keneanung** [comment] 2017-03-22 20:18
Closed with #29  (I hope)

**Closed by keneanung** 2017-03-22 20:18 UTC
